version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: '02:00'
      timezone: America/Tijuana
    groups:
      npm-dependencies:
        patterns:
          - '*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: '03:00'
      timezone: America/Tijuana
    groups:
      actions-dependencies:
        patterns:
          - '*'
