name: Diamond Scraper CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      # Paso agregado y corregido para Ubuntu 24.04
      - name: Install OS Dependencies for Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev libnss3 libatk-bridge2.0-0 libxcomposite1 libxrandr2 libasound2t64

      - name: Install Puppeteer Browser
        run: npx puppeteer browsers install chrome

      - name: TrimCache Execution
        run: |
          rm -rf ~/.config/google-chrome
          rm -rf /tmp/.com.google.Chrome*
          rm -rf ~/.cache/puppeteer
          echo "Sistema pulido y listo para el siguiente evento."

      # - name: Run Script
      #   run: node index.js
