# This workflow will update the pinned browsers

name: 'Update the pinned browsers'

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    # Run everyday at: https://crontab.guru/#0_6_*_*_*.
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update-chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          cache: npm
          node-version-file: '.nvmrc'
      - uses: google/wireit@f21db1f3a6a4db31f42787a958cf2a18308effed # setup-github-actions-caching/v2.0.3
      - name: Install npm dependencies
        run: npm ci
      - name: Build Puppeteer
        run: npm run build -w puppeteer
      - name: Update Chrome to latest stable version
        id: update
        run: |
          node tools/update_browser_revision.mjs
        env:
          BROWSER_TO_UPDATE: 'chrome'
      - name: Create Pull Request
        if: ${{ steps.update.outputs.commit }}
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: browser-automation/update-browser-version-chrome
          delete-branch: true
          commit-message: ${{ steps.update.outputs.commit }}
          title: ${{ steps.update.outputs.commit }}
          body: 'Automatically generated by https://github.com/moranricardo/puppeteer/blob/main/.github/workflows/update-browser-pins.yml'
          labels: full-ci

  update-firefox:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          cache: npm
          node-version-file: '.nvmrc'
      - uses: google/wireit@f21db1f3a6a4db31f42787a958cf2a18308effed # setup-github-actions-caching/v2.0.3
      - name: Install npm dependencies
        run: npm ci
      - name: Build Puppeteer
        run: npm run build -w puppeteer
      - name: Update Firefox to latest stable version
        id: update
        run: |
          node tools/update_browser_revision.mjs
        env:
          BROWSER_TO_UPDATE: 'firefox'
      - name: Create Pull Request
        if: ${{ steps.update.outputs.commit }}
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: browser-automation/update-browser-version-firefox
          delete-branch: true
          commit-message: ${{ steps.update.outputs.commit }}
          title: ${{ steps.update.outputs.commit }}
          body: 'Automatically generated by https://github.com/moranricardo/puppeteer/blob/main/.github/workflows/update-browser-pins.yml'
          labels: full-ci
